Add Starfield support
rockerbacon/modorganizer2-linux-installer pull request #618
Opened 2024-04-26 04:46 UTC by sapphiria39

Hello, I'm pretty new to using GitHub so apologies if this isn't the right way of doing this.

I've added support for Starfield based on the comments here: #528

Since this requires MO2 v2.5.0, I added a mechanism for overriding the `mo2_url` via `game_mo2_url` in the `gamesinfo` scripts. It's also necessary to use Proton 9.0 (beta). And I needed to add a workaround for `Data/SFSE/SFSE.ini` to point to `_Starfield.exe`, similar to the Skyrim VR workaround.

I installed a handful of the popular mods and that all seemed to work. Would be good to have some others test it out as well.

It does feel a bit hacky to use `game_mo2_url` like this though, so I'm open to waiting until we've got the Proton 9 and MO2 v2.5.0 changes in place.

2024-05-01 15:50 UTC, rockerbacon requested changes
The MO2 and Proton updates are two separate issues. #582 #543 

Please include only the Starfield changes in this PR. You can submit separate PRs for updating MO2, as well as the recommended Proton version.

2024-05-11 19:33 UTC, sapphiria39 commented
Alright, I reverted the MO2 & Proton changes and re-tested the setup after merging latest.

2024-05-11 20:06 UTC, rockerbacon approved these changes

2024-05-11 20:06 UTC, rockerbacon commented
Thank you for your contribution!

2024-05-11 20:06 UTC, merged